### ISSUE TITLE
API Nit: AsteriusStatics is unwieldy to use since it requires grouping by type

### ISSUE THREAD

**Issue by bollu** [tweag/asterius#118]
I presume that the style of storing statics as `[(type, [variables])]` makes code generation easier. However, this makes using it quite awkward, since the API strongly suggests that variables having the same type ought to be in the same `AstetiusStatics` section.  However, the API is not used that way. Instead, we seem to have _single variable lists_.

So, we should change the type to:
`[(type, variable)]`.

This will allow us to simplify the `AsteriusModule` from:
```hs
data AsteriusStatic
  = SymbolStatic AsteriusEntitySymbol
                 Int
  | Uninitialized Int
  | Serialized SBS.ShortByteString
  deriving (Eq, Ord, Show, Generic, Data)

instance Binary AsteriusStatic

data AsteriusStaticsType
  = ConstBytes
  | Bytes
  | InfoTable
  | Closure
  deriving (Eq, Ord, Show, Generic, Data)

instance Binary AsteriusStaticsType

data AsteriusStatics = AsteriusStatics
  { staticsType :: AsteriusStaticsType
  , asteriusStatics :: [AsteriusStatic]
  } deriving (Eq, Ord, Show, Generic, Data)


data AsteriusModule = AsteriusModule
  { staticsMap :: LM.Map AsteriusEntitySymbol AsteriusStatics
  , staticsErrorMap :: LM.Map AsteriusEntitySymbol AsteriusCodeGenError
  , functionMap :: LM.Map AsteriusEntitySymbol Function
  , functionErrorMap :: LM.Map AsteriusEntitySymbol AsteriusCodeGenError
  , ffiMarshalState :: FFIMarshalState
  } deriving (Eq, Show, Generic, Data)
```

to:
```hs
data AsteriusStatic
  = SymbolStatic AsteriusEntitySymbol
                 Int
  | Uninitialized Int
  | Serialized SBS.ShortByteString
  deriving (Eq, Ord, Show, Generic, Data)

instance Binary AsteriusStatic

data AsteriusStaticsType
  = ConstBytes
  | Bytes
  | InfoTable
  | Closure
  deriving (Eq, Ord, Show, Generic, Data)

instance Binary AsteriusStaticsType

data AsteriusModule = AsteriusModule
  { staticsMap :: LM.Map AsteriusEntitySymbol (AsteriusStaticsType, AsteriusStatic)
  , staticsErrorMap :: LM.Map AsteriusEntitySymbol AsteriusCodeGenError
  , functionMap :: LM.Map AsteriusEntitySymbol Function
  , functionErrorMap :: LM.Map AsteriusEntitySymbol AsteriusCodeGenError
  , ffiMarshalState :: FFIMarshalState
  } deriving (Eq, Show, Generic, Data)
```

that is, we should be able to get rid of the intermediate `AsteriusStatics`

**Comment by TerrorJack** [comment]
The `AsteriusStatics` type models the `CmmStatics` type in GHC API, see https://downloads.haskell.org/~ghc/8.6.5/docs/html/libraries/ghc-8.6.5/Cmm.html#t:CmmStatics

The point is: after your refactoring, now every `AsteriusStatic` (which models `CmmStatic`) must have its own symbol, which is obviously not the case since we often handle a `CmmStatics` with multiple `CmmStatic`s.

It's still possible to do this, e.g. when generating code, squashing all `CmmStatic`s into a single `AsteriusStatic`. But now `AsteriusStatic` will become more complicated, e.g. when we have interleaved symbols and raw bytes, the current `AsteriusStatic` definition won't be able to handle it.

**Comment by bollu** [comment]
I see. Thanks! I did not know that it was meant to mirror `CmmStatics`. I presume every `AsteriusXXX` is meant to mirror `CmmXXX`?

**Comment by TerrorJack** [comment]
> I presume every AsteriusXXX is meant to mirror CmmXXX
We closely mirror the Cmm IR types, but not always 1-to-1. e.g. `CmmType` contains `CmmWidth`, but we don't have an extra width type.
