### ISSUE TITLE
Consider using Test.Tasty.Golden for ghc test suite

### ISSUE THREAD

**Issue by bollu** [tweag/asterius#131]
Currently, we load the files into memory and compare them using string comparison. This is inferior since we sometimes get _huge_ error messages if the output of the test case is large. For example, see `test/ghc-testsuite/numeric/arith003.hs:`.

In general, using the `Test.Tasty.Golden` package ought to provide us with the same functionality (test against the `stdout` and `stderr` files) but a much better experience: This library prints out the _diffs_ when the test case fails, thereby making the output clearer.

It remains to be seen if the API is compatible, however.

**Comment by TerrorJack** [comment]
Let's do this then, it helps to make the report file cleaner, which will be generated and inspected a lot in our bug-bashing workflow.

**Comment by TerrorJack** [comment]
Closing for now due to inactivity. Btw, we have a script from a zurihac contributor which runs host ghc on testsuite.
