### ISSUE TITLE
configure.ac does not pick up the right values for auto-generated constants such as AC_CHECK_SIZEOF

### ISSUE THREAD

**Issue by bollu** [tweag/asterius#147]
Consider the program:

```hs
{-# LANGUAGE CPP #-}

#include "HsBaseConfig.h"

main :: IO ()
main = print (SIZEOF_STRUCT_MD5CONTEXT :: Int)
```

If run by `ahc-link --input-hs md5.hs --run`, it outputs `0`. Clearly, `configure.ac` is borked here. We need to figure out why.

The current dirty hack is to replace all values of `SIZEOF_STRUCT_MD5CONTEXT` by using native GHC to print the size. However, this is _clearly_ a hack.

Issue found while implementing  #146

**Comment by TerrorJack** [comment]
`autoconf` now properly detects `SIZEOF_STRUCT_MD5CONTEXT`, and our hack to manually specify it as a `#define` has been removed.
