### ISSUE TITLE
[EXPERIMENT] Consider transpiling cbits & RTS from C to Javascript/WASM

### ISSUE THREAD

**Issue by bollu** [tweag/asterius#148]
### C to JS
Rewriting large parts of `cbits` is quite painful. It might make sense to simply transpile it from C to JavaScript using the `libclang` API, or higher level wrappers around `libclang` such as [`cppast`](https://github.com/foonathan/cppast)

##### Advantages
- High level constructs map to similar high level constructs (loops, conditionals, etc) so it should simplify life. Similarly, array indexing / struct member referencing will cleanly map to `rts.memory.loadXX` calls. 

- Static data that is declared can also be easily code generated as a module member.

##### Disadvantages

- Cannot handle wild C constructs such as `goto` or `setjmp/longjmp`. `goto` does exist in the RTS, if not in the `cbits` of the library.

- I don't particularly know the `libclang` API off hand, though I've played with it once.

### C -> LLVM -> (edit) -> WASM

We can generate LLVM using `clang`, and we can then monkey patch the `LLVM` to convert loads and stores to our custom memory interface correctly.

##### Advantages

- Correctly deals with all of the C, so this can be used to transpile the RTS as well as the cbits.

- I have extensive experience monkey-patching LLVM to do weird things.

##### Disadvantages

- I currently do not know how things such as accessing member functions of another module is represented within LLVM for wasm. So, we need to figure out how to invoke things such as `memory.loadXX` / `memory.storeXX` from another module, how to access `this.xxx`, etc.

- In general, we need to understand how the lowering from LLVM to WASM happens, and how we can perform inter-module and intra-module communication.

**Comment by bollu** [comment]
- `cppast` is out the game, it cannot parse function bodies [as mentioned in the blog post](It also does not parse function bodies)

**Comment by TerrorJack** [comment]
The long term solution imho is still introducing the clang toolchain; that'll go into its own issue when the time comes.
