### ISSUE TITLE
Binaryen on the single-function approach

### ISSUE THREAD

**Issue by kripken** [tweag/asterius#19]
Hi! Reading [this interesting post](https://www.tweag.io/posts/2018-05-29-hello-asterius.html) I saw

> One possible solution is to transform the program by collecting all Cmm functions into one WebAssembly function [..] We experimented with this approach and discovered that with a large number of blocks in a single function, binaryen is not sufficiently scalable for this approach to be practical.

Is that approach still interesting for you? Would it be useful if we looked into improving binaryen in that area?

**Comment by TerrorJack** [comment]
@kripken Hi, yes it is. In fact I once opened a related issue in binaryen about this: https://github.com/WebAssembly/binaryen/issues/1493

In order to expose the validation bottleneck of "lots of blocks in a single function", I can write a program that uses binaryen to emit such a module and attempt to validate it. Does that sound useful to you?

**Comment by kripken** [comment]
Thanks @TerrorJack, I thought this sounded familiar :)

Ok, re-reading that discussion, I see I landed a PR that sped up parsing by 10x on a testcase. Do you still see a problem after that? If so then yes, a program showing the issue would be useful, that's definitely something we should fix.

**Comment by TerrorJack** [comment]
@kripken I remembered parsing wasn't a problem (we don't need to parse anyway), but validation was. I wrote a simple program here: https://gist.github.com/TerrorJack/9943e24dd4bd325e0725e7b2322ffb54

The idea is simple: generate a function of type `i32 -> i32`, it contains a deep chain of nested blocks; at the bottom is a `br_table` which branches to a block according to the parameter, and following the end of each block is an assignment to a local reg. The local reg is then returned. It's an over-simplified case of "lots of blocks within one function" which asterius will need to handle.

**Comment by kripken** [comment]
Thanks @TerrorJack!

I opened #1576 with optimizations there. The validator just hadn't been optimized much yet, that PR makes it almost 3x faster on that testcase. After that, the time spent to validate is not surprisingly large compared to the time to build.

**Comment by TerrorJack** [comment]
@kripken Very amazing speed for a fix! Will try the alternative approach later and see if it works.

Regarding the original issue I posted in binaryen: are you familiar with other language runtime's need of a computed goto? Do they handle that simply with a `br_table`, or something fancier? Thanks a lot!

**Comment by kripken** [comment]
By computed goto do you mean a goto to a location determined by a pointer whose value is known at runtime? In general `br_table` is the best tool there, yeah. (I believe the wasm spec process considered adding more things, but nothing concrete yet afaik.)

**Comment by TerrorJack** [comment]
Switching to single-function approach requires work at:

* `Asterius.Types`, we need to remove the `CFG` variant of `Expression` and add the variant to `Function` instead.
* `Asterius.CodeGen`: we can't marshal the Cmm local/global regs in codegen.
* `Asterius.Resolve`: we need extra care to "layout" all Cmm local regs to wasm local vars, and ensure one Cmm function's local regs don't accidentally collide with other function's local regs.

Given the workload of refactoring, we'll stay with the current approach and prioritize on other issues first.
