### ISSUE TITLE
Support cryptonite

### ISSUE THREAD

**Issue by flokli** [tweag/asterius#192]
Cryptonite is pretty commonly used in Haskell world.

This is a tracking issue for all the bits required to make it work.

Possible users: [hnix](https://github.com/haskell-nix/hnix/pull/504), [reverse deps from packdeps.haskellers.com](https://packdeps.haskellers.com/reverse/cryptonite)

**Comment by TerrorJack** [comment]
Closing for the moment due to inactivity. `cryptonite` is surely a nice to have, but it's pretty way up the dep tower; we'll focus on ensuring some simpler stuff like `aeson` works fine before `cryptonite`.
