### ISSUE TITLE
`read` function returns incorrect values for Doubles and Floats

### ISSUE THREAD

**Issue by space-shell** [tweag/asterius#208]
Hi,

The using the `read` function to parse Float and Double values from a string returns incorrect values.

The Gist below shows a minimal setup which includes the asteruis example code for converting and printing values from Haskell to JavaScript.

[Example Gist](https://gist.github.com/space-shell/d8902a9d380e4b36a80a2448c2e621cc)

For the input string "1.2" I am receiving the value 1.5

Thanks

**Comment by bollu** [comment]
Thanks a lot for the bug report! This should be fixed now.
