### ISSUE TITLE
Fix broken `stg_enter_ret` and `stg_ap_0_fast`

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#22]
Right now, the codegen outputs broken code for `stg_enter_ret`, which makes `stg_returnToStackTop` accidently ignores `Main_main_closure` on the stack. We hardcoded a version of `stg_enter_ret` that's known to work in `Asterius.Builtins`, but the hack doesn't make the underlying issue go away.

Another potentially broken function is `stg_ap_0_fast`, it pre-maturely jumps to 0, which aborts execution without even entering `StgReturn`. This error often shows up when compiling code related to `GHC.List`.

**Comment by TerrorJack** [comment]
Fixed by replacing binaryen's relooper with our own conservative relooper, trading performance for reliability. A rare bug of binaryen's relooper is spotted when generating code for `stg_ap_v_ret`, which doesn't return to `StgRun` at the correct timing.

**Comment by kripken** [comment]
@TerrorJack - any chance you have a testcase that I can reproduce that binaryen relooper bug? I'd love to fix it :) (regardless of whether you're still using that code)

**Comment by TerrorJack** [comment]
@kripken I'd love to. The problem is: I have the problematic binaryen IR in Haskell land, but how do I pass it to you? Marshalling to wasm already invokes the relooper.

**Comment by TerrorJack** [comment]
@kripken Is there some JSON-like format of binaryen IR that I can emit?

**Comment by kripken** [comment]
Are you using the C API? Then we have a neat trick there, the tracing option, see https://github.com/WebAssembly/binaryen/blob/master/src/binaryen-c.h#L858 - basically, call `BinaryenSetAPITracing(1)` before anything, then call `BinaryenSetAPITracing(0)` after generating the IR, and it will print out a full testcase in c++ source form.

**Comment by TerrorJack** [comment]
@kripken Thanks for the reminder. The output of tracing is at https://gist.github.com/TerrorJack/11cd6c13ff51f2d3b72f0616b1b318ab, and the broken function to look into is `stg_ap_v_ret`.

The body of `stg_ap_v_ret` is a block consisted of a relooper graph and a `GetLocal` which indicates return value. When a relooper block with no `AddBranch`/`AddBranchForSwitch` is entered, the wasm "return value local variable" is assigned, then the relooper graph should exit. The observed buggy behavior: after that block is entered, control flow branches to another block instead of exiting the whole graph.

Let me know if you need any additional context info!

**Comment by kripken** [comment]
Thanks @TerrorJack!

Reading your description, this may be confusing documentation - if a block has no branches out, the relooper assumes it includes a terminator. That is, it assumes the block's contents end in a `return` or `unreachable`. Without that, it may indeed flow into another block, in a way that seems random.

Does that sound like what's going on here? If so, were there any specific docs that we could have improved? I wonder if we can add an assertion for this as well. But not sure we can do more than that - we can't emit an `unreachable`, and we don't know what value to use in a `return`.

(Separately, trying the output I see what seems to be a trace-emitting bug, I'll look into that.)

**Comment by TerrorJack** [comment]
@kripken Yes, that is very likely the cause. I didn't find any description about the "terminator" assumption when I was reading binaryen docs. Can you add it to https://github.com/WebAssembly/binaryen/wiki/Compiling-to-WebAssembly-with-Binaryen#cfg-api, and also probably as a comment in `binaryen-c.h`, so other compiler authors don't get confused too? And an assertion failure (or warning) will definitely help.

Indeed I wasn't putting a `return` at the end of exit blocks. The practice of assigning return value to a local var instead of direct returning was a workaround to make binaryen validator happy: we can assume the value type of every relooper block code is `none`.

**Comment by TerrorJack** [comment]
@kripken Also, regarding trace emitting: I'm having difficulty getting a complete trace when the module gets large (about ~3MB as serialized wasm binary), the trace stops somewhere. Also, is it possible to provide an option to redirect tracing output to a file, instead of forcing to stdout?

**Comment by kripken** [comment]
Thanks, I opened https://github.com/WebAssembly/binaryen/pull/1617 with docs in the tree, and also added a section in https://github.com/WebAssembly/binaryen/wiki/Compiling-to-WebAssembly-with-Binaryen#cfg-api

Odd about the large trace issue. I suppose we could add a file option, but it's just printing to stdout - that should work by just piping stdout to a file? What shell environment are you in?

**Comment by TerrorJack** [comment]
@kripken Yeah I'm piping to stdout, both in PowerShell and msys2 bash, both have the same issue. And there's value of adding file option, since the program which calls binaryen C API may also output its own messages, possibly interleaving with tracer's output.

**Comment by kripken** [comment]
I see, makes sense. I opened https://github.com/WebAssembly/binaryen/issues/1618 for that.

**Comment by TerrorJack** [comment]
@kripken Adding `return` at the end of terminator blocks seem to cause type errors though. Here's a minimal example:

```
(module
 (type $func_type (func (result i32)))
 (func $func (; 0 ;) (type $func_type) (result i32)
  (local $0 i32)
  (nop)
  (block $switch$2$leave
   (block $switch$2$default
    (block $switch$2$case$1
     (br_table $switch$2$case$1 $switch$2$default
      (get_local $0)
     )
    )
    (block
     (block
      (return
       (i32.const 19)
      )
     )
    )
   )
   (block
    (block
     (return
      (i32.const 233)
     )
    )
   )
  )
 )
)
```

It's a function which reads local $0, if it's 0 then branch to another relooper block which simply returns 19, otherwise branch to a block which returns 233. However, the validator complains:

```
[wasm-validator error in function $func] 1 != 0: function body type must match, if function returns, on
[none] [none] (block
 [none] (nop)
 [none] [none] (block $switch$2$leave
  [none] (block $switch$2$default
   [none] (block $switch$2$case$1
    [unreachable] (br_table $switch$2$case$1 $switch$2$default
     [i32] (get_local $0)
    )
   ) ;; end block $switch$2$case$1
   [unreachable] [unreachable] (block
    [unreachable] (block
     [unreachable] (return
      [i32] (i32.const 19)
     )
    ) ;; end block
   ) ;; end block
  ) ;; end block $switch$2$default
  [unreachable] [unreachable] (block
   [unreachable] (block
    [unreachable] (return
     [i32] (i32.const 233)
    )
   ) ;; end block
  ) ;; end block
 ) ;; end block $switch$2$leave
) ;; end block
```

Am I missing anything here? Thanks!

**Comment by kripken** [comment]
That does sound like a bug. It must be in the relooper code, since the wast you pasted is valid - so the intermediate IR from the relooper must be wrong. Can you please use tracing to create a C testcase for that small example?

**Comment by TerrorJack** [comment]
@kripken Sure, here it is: https://gist.github.com/TerrorJack/093b65141e3f0c798ac255fad4d42278

**Comment by kripken** [comment]
Hmm, I don't see it fail on 1.38.8. Adding a BinaryenModulePrint after validation, it prints out the module ok too. However, the module looks slightly different in terms of placement of blocks - something may be going wrong in the trace generation perhaps, or perhaps results differ by platform (how stdlibc++ does hashing might matter, in theory, although it shouldn't).

Maybe you can write out the steps I'd need to do to run things exactly as asterius does when it hits the bug? (bearing in mind I've never built or used it...)

**Comment by TerrorJack** [comment]
@kripken I can provide a nix expression or a docker image, so you can reproduce exactly the minimal case above by running a command and see the trace. Which one do you prefer?

**Comment by kripken** [comment]
Docker would be easier for me I think, thanks (although I've not used docker before). Before that, though, I had a simpler idea - when you run the C++ output from the trace, does it fail for you like the original program did?

**Comment by TerrorJack** [comment]
@kripken It doesn't. I tested compiling the trace and linking it with exactly the same static `binaryen`, but validation simply returns 1. So it seems the problem is not at `binaryen`'s end.

**Comment by TerrorJack** [comment]
@kripken Does binaryen relooper depend on specific CPP/linker flags to work properly?

**Comment by kripken** [comment]
@TerrorJack Very strange...

The relooper should work fine in all flags - we probably test only -O2 (linux) on CI, but people do build locally on various platforms and opt levels, and I'm not aware of open issues there.
