### ISSUE TITLE
Related Packages List

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [tweag/asterius#224]
Is there a list of packages that enhance the js ffi?

**Comment by TerrorJack** [comment]
> enhance the js ffi

Perhaps you mean "makes use of the js ffi"? We plan to get a version of `jsaddle` working later.

In general, a list of packages that guarantee to work with asterius isn't prepared yet. That requires extra time to work on a stackage-like infra to run CI on a package set, including their tests and catch regressions. We're focusing on delivering currently lacking features for now (e.g. Template Haskell).
