### ISSUE TITLE
Prototype JavaScript FFI

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#23]
Right now it's already possible to implement a prototypical JavaScript FFI, without needing to wait for `host-bindings` or `gc` proposal of WebAssembly land in V8.

The main trick is: instead of directly passing JavaScript references across WebAssembly/JavaScript boundary, we only pass a handle and the JavaScript runtime maintains the mapping from handles to real objects. The JavaScript runtime and our own storage manager do not collaborate in any way, and manually calling something like `freeHaskellFunPtr` is required to avoid leaking on the JavaScript side.

A brief list of what work it takes and what we can achieve:

* Without touching the type-checking procedure of ghc, we can't have `foreign import javascript` syntax working in the ghcjs way. Instead, we'll supply a separate file to `ahc-link` describing what to import, and `ahc-link` will make the relevant bindings available.
* `foreign import` is relatively easy to implement: we can import any JavaScript object as a handle, and "calling" a JavaScript function is simply sending a handle list to the JavaScript side and the real work happens out of wasm.
* `foreign export` is a lot more difficult since it requires the scheduler to properly support interrupting/resuming Haskell threads.
* It's possible to calculate a JavaScript snippet in the wasm world, then using that snippet as the import schema. This requires finishing CString-related utils first.

Some test suites demonstrating importing Web API functions will be implemented.

**Comment by TerrorJack** [comment]
A prototype of `foreign import javascript` is implemented, see https://github.com/tweag/asterius/blob/master/asterius/test/jsffi/jsffi.hs for a quick example.

**Comment by TerrorJack** [comment]
JSFFI is further improved by inserting wrapper functions at the Haskell/Wasm boundary, so it becomes possible to perform marshalling before passing values between Wasm/JS, making more Haskell types (e.g. `Char`) able to cross FFI boundary.

Next goal: supporting importing async JS computation.

**Comment by TerrorJack** [comment]
Further work in JavaScript FFI come in two directions:

* Improve the runtime infrastructure, so the scheduler supports interrupting/resuming a Haskell thread, which is essential when Haskell/JavaScript computations are interleaved
* Improve `foreign import javascript` syntax, use supplementary input other than `.hs` to make it possible to instantiate some context (e.g. `require` some foreign library)

**Comment by TerrorJack** [comment]
The info required to handle `foreign import javascript` is now properly persisted along with ordinary IR per module, previously there's only in-memory linking of non-boot modules. This makes it possible to implement a boot package (something like `asterius-base`) which uses `foreign import javascript`, and later use that code for user's input program.

**Comment by TerrorJack** [comment]
There is ongoing work on the `wip-gen2-scheduler` branch which improves the storage manager/scheduler to address the issues mentioned above.

Currently, we have:

* Factored out `hs_init` out from `main`. After one initialization, it's possible to enter `main` multiple times, each time initializing its own thread state. Different `main` IO actions can be entered, provided they are CAFs and the symbol can be fed to `rts_evalLazyIO`. This is one first step towards calling Haskell from JavaScript.

* Heap size can be specified via `ahc-link --heap-size`, previously it was hard-wired to 1GB.

The scheduler still assumes run-to-completion though, and more work is needed to make interrupting/resuming threads work.

**Comment by TerrorJack** [comment]
Progress on this front:

* Support for `StablePtr` is merged. When we hand a Haskell closure to the JavaScript land, we can't pass a raw heap pointer, instead we need call `newStablePtr` at runtime and pass the result. (Static closures are of course an exception)

* Added an `rtsapi` test suite that demonstrates calling a Haskell function the JavaScript way.

The rest is implementing the `foreign export javascript` syntactic sugar, plus a few more `RtsAPI` interfaces to make it work for all basic JSFFI types.

**Comment by TerrorJack** [comment]
The implementation of `foreign export javascript` is working and tested in `jsffi` unit test. Merged in `master`.

**Comment by TerrorJack** [comment]
It's possible to deal with asynchronous JavaScript computation without implementing an IO manager in rts:

* In `rts.js`, we implement `makeHaskellCallback` that converts a `StablePtr (IO ())` or `StablePtr (JSRef -> IO ())` to the `JSRef` of JavaScript lambda which upon invocation, reads the SPT and triggers evaluation with rts api.
* `makeHaskellCallback` can be imported back to Haskell using `foreign import javascript`.
* Using `newStablePtr`, we can make arbitrary callback continuation into a `StablePtr`, then into any `JSRef`.
* The `JSRef` produced from a Haskell continuation can be fed to another JavaScript function that expects a vanilla JavaScript callback (e.g. `setTimeout` or `EventTarget.addEventListener`).

`makeHaskellCallback` is implemented for nullary/unary Haskell callbacks, and an example which passes a Haskell continuation to `setTimeout` is present in `jsffi` unit test.

**Comment by crocket** [comment]
You probably want to implement https://github.com/WebAssembly/proposals/issues/12

**Comment by TerrorJack** [comment]
@crocket Not really :) The anyref proposal is more relevant, but we currently don't use those opcodes either.

**Comment by crocket** [comment]
Are you saying that FFI to WebAssembly modules(EcmaScript 2015 modules) will not be supported by asterius?

**Comment by TerrorJack** [comment]
The ESM proposal isn't on our schedule for the moment.

**Comment by TerrorJack** [comment]
JSFFI has already evolved a lot since last activities on this issue: async JSFFI, support for type synonyms and newtypes, etc. Closing this one for now; remaining todos in the JSFFI will be opened as separate issues.
