### ISSUE TITLE
Implement tail call opcode support for the `binaryen` backend

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#266]
Right now, we have tail call opcode support for the `wasm-toolkit` backend, which uses native `return_call` and `return_call_indirect` to avoid trampolining for cmm function calls. The `binaryen` library already supports tail call opcodes now, so it's good timing to update our in tree `binaryen`, and implement tail call opcode for the `binaryen` backend as well.

**Comment by curiousleo** [comment]
This is the PR that added tail calls to `binaryen`: https://github.com/WebAssembly/binaryen/pull/2197/. It is part of https://github.com/WebAssembly/binaryen/releases/tag/version_85 and later versions.
