### ISSUE TITLE
Errors attempting to reproduce local build

### ISSUE THREAD

**Issue by pimlu** [tweag/asterius#29]
Hello again, I think I might have a PR to fix a bug, but I can't test it because I haven't gotten local builds to work yet.

I'm building with the same script/command as the resolved #28 (except with `stack exec`).  `ahc-link` will run without issue but the generated wasm fails.

I get `[ERROR] Uninitialized memory trapped at 0x00000000` (and subsequently, `RuntimeError: unreachable` which apparently always happens).  `--debug` says it entered `mult_hs` and did some work before it failed.

From here I'm not really sure how to debug.  Any help would be appreciated!

I'm running this in OpenSUSE Tumbleweed.

**Comment by TerrorJack** [comment]
@pimlu Hi, can you try run the "jsffi" and "rtsapi" unit test first, and paste the output here? A `stack test asterius:jsffi` should do the trick.

**Comment by TerrorJack** [comment]
@pimlu Hi, what's the exact git revision of `asterius` are you building? I'll try to reproduce in an OpenSUSE environment here.

Also, did you try running the exact same input and command line args on the pre-built docker images? The images are pushed only when unit tests pass, and I confirm `jsffi` and `rtsapi` compiles and runs normally with the latest image of `master` branch.

If you're building & booting based on latest rev of `master`, this should indicate some hidden indeterminism in either GHC or asterius. One possible lead to follow would be: use the `ahc-link --debug --output-ir` flags, redirect the node.js debug logs to different text files and attempt to diff them to see at what point control flow really diverges. Can you additionally post the dumped IR and debug logs of those two unit tests? Simply use `stack test asterius:jsffi --test-arguments="--debug --output-ir"`. Thank you very much!

**Comment by pimlu** [comment]
Yeah, originally when I got this stuff to work in #28 I was using the pre-built docker images, which don't seem to have issues.  It's my local build that is having new behavior.

I can confirm I'm on master (revision ad3030f).  Helpful note with setting up OpenSUSE Tumbleweed: in addition to the dependencies [here](https://tweag.github.io/asterius/building/#extra-dependencies) it won't build without ncurses6, gmp, and numa.

Here's the results for those tests on ad3030f: https://gist.github.com/pimlu/89632521b8b5112c9c518ebc72d04689 I pasted the command I used to generate the files at the top of each file.

**Comment by TerrorJack** [comment]
@pimlu Hi, apologies for late reply. I haven't got luck reproducing the problem in my local environment, but in case you're still interested, can you test 900e09a instead? (Latest `master` rev as of now). It's a mega commit which switches away from binaryen and base on our own wasm engine by default and fixes some critical issues, so things might have improved there.

**Comment by pimlu** [comment]
Yes, the mega commit (actually because I was late too, e795f8bf199e277ae98115440efedec019671789) fixed it! `hs_mult` is working perfectly and locally.

As I'm working my way up to building the [project using haste](https://github.com/pimlu/fractran), my next step is foreign exported `String -> String` calls from JS with JSRefs.

 The fix I was working on made my test code build successfully but it still failed running wasm. The patch refactored [this line](https://github.com/tweag/asterius/blob/e795f8bf199e277ae98115440efedec019671789/asterius/src/Asterius/JSFFI.hs#L525) to match [this one](https://github.com/tweag/asterius/blob/e795f8bf199e277ae98115440efedec019671789/asterius/src/Asterius/JSFFI.hs#L486) and was kind of speculative. It produced a wasm file that failed when I called the `String -> String` function.  I took a look at it seems to be the direct exported wasm function (taking f64 and returning an f64), so is there a way to allocate a JSRef inside `--asterius-instance-callback` that I'm missing?  I tried changing it to be `Int -> String` to see what it would return and it failed a little later instead.

Maybe I'm using it wrong, and I should set it up another way with foreign import javascript? [This is the test code](https://gist.github.com/pimlu/e22e7de3a973d50e9728bb19cd71b844) I used, it largely copied the example FFI code to get `toJSString`/`fromJSString` and then tries to make basic test exports from them.

Thanks for your patience with me!

**Comment by TerrorJack** [comment]
@pimlu Hi, thanks for catching that line of bug! I'd be happy to merge a PR for it :)

Regarding the handling of `JSRef`s and usage of `--asterius-instance-callback`: the "instance" object returned by `newAsteriusInstance` in `rts.js` doesn't export methods to directly manipulate `JSRef`s, so currently with an "instance", you can't allocate a `JSRef`. But now that you mention it, it looks like a useful feature so I'll soon add methods to allow `JSRef`/`StablePtr` allocation/inspection in JavaScript.

The JSFFI blog post didn't contain comprehensive explanation of what an "instance" is capable of, and how it can be used in JavaScript. The `--asterius-instance-callback` switch was a quick dirty command line argument to allow *some* degree of freedom when generating the final `.js` file, but we'll soon have a more principled approach which allows one to supply custom logic via ES6 modules instead.

I haven't got time to do an in-depth debugging for your failed case though, but thanks for spotting the failure, I'll get to it sometime and keep you updated :)

**Comment by TerrorJack** [comment]
Closing for the moment due to inactivity. The JavaScript interface for interacting with the "asterius instance" object will be documented, so is JS/HS interop.
