### ISSUE TITLE
Diagrams example

### ISSUE THREAD

**Issue by hsyl20** [tweag/asterius#315]
This issue tracks the status of the [Diagrams example](https://github.com/hsyl20/asterius/tree/hsyl20-diagrams)

- [ ] Write a blog post. Mention:
    * Cabal isn't supported and we pulled the dependencies manually.
    * We had to modify ``lens`` because of a "clever" hack relying on lenses being in their own package (build TH names without using TH extension in order to support Stage 1 compilers)
    * CPP included files had to be copied close to their including modules in order to be found
    * Some random failing stuff has been disabled (some class instances, some native zlib stuff for image codecs, etc.)
- [ ] The example relies on the `asterius-TH` branch. Ultimately this branch should be merged.
- [ ] Currently the code fails: `undefined` BigInt (or infinite loop in `yolo` mode)

**Comment by TerrorJack** [comment]
The example works and the blog post is published a while ago.
