### ISSUE TITLE
Builtin `aeson` support

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#347]
In the existing haskell-to-web use cases, `aeson` is still the dominant standard for marshaling Haskell data structures to JavaScript (and vice versa). We shall support `aeson` out-of-the-box:

* [x] Install and ship `aeson` into the global pkgdb using `ahc-cabal`
* [x] Base `asterius-prelude` on top of `aeson`
* [x] Implement runtime functions related to UTF-8 JSON encoding/decoding
* [x] Examples and tests

**Comment by therewillbecode** [comment]
Watching this with interest.

**Comment by TerrorJack** [comment]
Using only standard `JSON`, `TextDecoder` and `TextEncoder` APIs, I can come up with roughly two different approaches for marshaling:

## Through strict `ByteString`s

This approach marshals Haskell values first to lazy `ByteString`s, then strict ones, then decode the UTF-8 buffer to a JS string, finally to a JS value, likewise for the other direction.

I'm concerned about the performance of this approach, a lot of buffer copying happens here. There are tricks to reduce one or two copying operations:

* When passing strict `ByteString` to the `TextDecoder`, we expose the linear memory pointer directly as a typed array.
* Before calling `TextEncoder`, we allocate the `ByteString` buffer and write into it with `encodeInto`.

## Through `Value`s

This approach marshals Haskell values to a `Value` directly, then build the JS value by traversing the `Value`. For the other direction, the `Value` is built directly either via a runtime function or a Haskell function using JSFFI.

Given we have fast `Text` and JS string codec, this one may be faster. But of course, a lot of extra trouble. And not using vanilla `JSON.parse` & `JSON.stringify` may be a correctness risk?

@hsyl20 Any thoughts which route to take?
@luite Can you provide some insight on how ghcjs accomplishes the conversion? Does it need to go through `ArrayBuffer` and JS strings?

**Comment by TerrorJack** [comment]
We implemented the codec between lazy `ByteString`s and `JSString`s, and decided to use `JSON.parse` & `JSON.stringify` on the js side. Directly working with `Value` closures on the heap seems might be a premature optimization for now.

**Comment by TerrorJack** [comment]
Closed via #363. May revisit in the future when proved to be a bottleneck.
