### ISSUE TITLE
Missing cbits for `primitive`

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#373]
`primitive` has its own set of functions for `memcpy`, `memmove`, `memcmp` and `memset`. Since it's used by `vector`, maybe this has a high impact on downstream dependencies.

**Comment by TerrorJack** [comment]
Places in the source code to look at:

* The cbits of `primitive` package: https://github.com/haskell/primitive/blob/master/cbits/primitive-memops.h
* How `primitive` imports the cbits: https://github.com/haskell/primitive/blob/master/Data/Primitive/Internal/Operations.hs
* How `primitive` generates the `Prim` instances for various types: https://github.com/haskell/primitive/blob/master/Data/Primitive/Types.hs

**Comment by gkaracha** [comment]
@TerrorJack thanks for the resources. I am still unclear though as to what does this issue require to be done in asterius, can you clarify?

**Comment by TerrorJack** [comment]
Closed by #542.
