### ISSUE TITLE
Garbage collector is very slow

### ISSUE THREAD

**Issue by hsyl20** [tweag/asterius#374]
Currently the garbage collector is very slow. As we can see in the following flame graph (diagrams' SquareLimit example running in Chromium), we spend most of the time in the garbage collector and only a small fraction of the time doing actual work (in pink on the left of "returnFromTSO").

![screenshot-20191205@174056](https://user-images.githubusercontent.com/96633/70255469-24952780-1787-11ea-99c3-98881a20fba3.png)

**Comment by TerrorJack** [comment]
A short-term mitigation we can easily implement: do not always enter gc when `performGC()` is entered. We can add a rts parameter specifying a threshold, and when the linear memory doesn't grow beyond the threshold, `performGC()` returns immediately and the rts only allocates fresh mblocks. We can also implement "idle gc" which performs gc when the TSO run queue is empty.

In the longer term, we should move away from naive copying collection to another algorithm.

**Comment by hsyl20** [comment]
PR #375 reduces the GC time on this example from ~150ms to ~65ms.

@TerrorJack  We should try your approach to get even better perf

**Comment by TerrorJack** [comment]
Should have been closed by #379.
