### ISSUE TITLE
Help exporting hello_world function from Haskell to JavaScript

### ISSUE THREAD

**Issue by Swiip** [tweag/asterius#41]
First of all, thanks for this great initiative. There is no good compiler of any functionnal language to Wasm and it will be great to have one for Haskell. Unfortunately, I'm still very noob with Haskell, compilers, and all but I try to digg into Wasm. Still, I succeed in using Asterius through Docker, thanks again. 

I'm trying to export from Haskell an `hello_world` function which takes a string as only argument and return an other one. The mult example worked fine. Unfortunately exporting a function which takes a String in arguments always failed, whatever the workaround I tried. I succeed to make it works returning a String but not receiving one.

There is the code I got:

```haskell
toJSString :: String -> JSRef
toJSString = foldl (\s c -> js_concat s (js_string_fromchar c)) js_string_empty

fromJSString :: JSRef -> String
fromJSString s = [js_string_tochar s i | i <- [0 .. js_length s - 1]]

foreign import javascript "\"\"" js_string_empty
  :: JSRef

foreign import javascript "${1}.concat(${2})" js_concat
  :: JSRef -> JSRef -> JSRef

foreign import javascript "${1}.length" js_length
  :: JSRef -> Int

foreign import javascript "String.fromCodePoint(${1})" js_string_fromchar
  :: Char -> JSRef

foreign import javascript "${1}.codePointAt(${2})" js_string_tochar
  :: JSRef -> Int -> Char

foreign import javascript "console.log(${1})" js_print :: JSRef -> IO ()

foreign export javascript "hello_world" hello_world :: JSRef -> JSRef

hello_world :: JSRef -> JSRef
hello_world name = toJSString ("Hello, " ++ (fromJSString name))

main :: IO ()
main = do js_print 42
```

But it fails with:
```
root@b31716e46fdd:~/2048# ahc-link --input mult.hs --export-function=hello_world --asterius-instance-callback=cb
[INFO] Loading boot library store from "/root/.stack-work/install/x86_64-linux/ghc-8.7/8.7.20181027/share/x86_64-linux-ghc-8.7.20181027/asterius-0.0.1/.boot/asterius_lib/asterius_store"
[INFO] Populating the store with builtin routines
[INFO] Compiling mult.hs to Cmm
[INFO] Marshalling from Cmm to WebAssembly
[INFO] Marshalling "Main" from Cmm to WebAssembly
[INFO] Attempting to link into a standalone WebAssembly module
ahc-link: No match in record selector hsTyCon
```

I tried importing JavaScript callbacks to change signatures, I succeed to pass the compilation step but never succeed to have my String in argument.

**Comment by TerrorJack** [comment]
@Swiip Hi, thanks for taking an interest. I'm currently improving Haskell/JavaScript interop, and we'll soon get rid of pasting those string conversion functions here and there (they belong to the standard library). Do let me know if you have additional problems :)

**Comment by Swiip** [comment]
@TerrorJack thanks for answering. Any improvement on the interop would be great.

To be honest, those string conversion function works pretty well and wasn't the problem. Bugs (I suppose) both in compile time and runtime in handling strings was far more complicated.

In fact, my ultimate goal is not hello world. If I can pass String both way, I can pass Jason, if I can pass Jason, I can pass whatever I want ;)

**Comment by Swiip** [comment]
New version I just checked has a way better management of JS types, it's cool thanks!
