### ISSUE TITLE
Use a Reader monad in Asterius.Backends.WasmToolkit

### ISSUE THREAD

**Issue by gkaracha** [tweag/asterius#522]
Similar situation as in Issue https://github.com/tweag/asterius/issues/515: Several read-only arguments are passed to `makeInstructions`, making it (a) longer and (b) more difficult to read. Also, extending this list of parameters means that we have to touch a lot of code unnecessarily (see e.g. PR #513). Instead, it would be better to use a `ReaderT` to capture all such parameters.

**Comment by TerrorJack** [comment]
Closed by #525.
