### ISSUE TITLE
Use newer Binaryen haskell bindings

### ISSUE THREAD

**Issue by mboes** [tweag/asterius#560]
**Is your feature request related to a problem? Please describe.**

Asterius currently uses the Haskell bindings for Binaryen found at https://github.com/tweag/haskell-binaryen/tree/asterius-200410. These embed a patched version of Binaryen itself. There are two build systems, Cabal for the bindings and CMake for the Binaryen source code, and the two need to be integrated. This is done using a custom `Setup.hs` script. This script is incorrect in at least two ways:

* if any source file in Binaryen changes, then `stack build` might not rebuild anything. That's because Cabal doesn't know the CMake dependency graph.
* it doesn't work on NixOS and possibly elsewhere.

The bindings on the `master` branch are simpler. There is no vendored copy of Binaryen, so we don't have to worry about two different build systems not seeing eye to eye. Binaryen from Nixpkgs or from the system is used, depending on the user's Stack configuration.

**Describe the solution you'd like**

Adapt Asterius to using the bindings on the `master` branch of `tweag/haskell-binaryen`. The `nix` stanza in that project's `stack.yaml` would need to be copied into the `stack.yaml` of Asterius. The Docker image should be changed to ship with a system installed version of Binaryen.

**Comment by TerrorJack** [comment]
Closed by #571.
