### ISSUE TITLE
[macOS] can not boot due to cmm miscompilation

### ISSUE THREAD

**Issue by angerman** [tweag/asterius#58]
For reasons that are not yet entirely clear to me. `ahc-boot` fails (assuming #57 fixed) to compile `.cmm` files properly.  The resulting assembly contains duplicate symbols with identical names:

```
.text
.align 3
Lc4l:
Lc4l:
        jmp Lc4u
.const_data
.align 3
.align 0
_Lc4l_info:
        .quad   Lc4l
        .quad   259
        .long   30
        .long   0
```

**Comment by TerrorJack** [comment]
Closing for the moment due to inactivity.
