### ISSUE TITLE
ahc-link produces node code when compiled with the --browser flag and not the --bundle flag

### ISSUE THREAD

**Issue by space-shell** [tweag/asterius#59]
When compiled with the --browser flag and not the --bundle flag, `ahc-link` produces node code that prevents the output from running in the browser

The following file contains an import from nodes 'fs' module

`rts.fs.mjs`

When the reference and its associated implementation are removed the project runs in the browser as expected.

**Comment by space-shell** [comment]
Thanks for the quick response, there's no rush to resolve the issue for myself personally but since im starting to experiment with asterius as a front-end developer i'll try to help out as much as I can.

**Comment by majkrzak** [comment]
I've started to fixing the issue, but I see that currently `NodeFileSystem` is not used and might be dropped :thinking:
