### ISSUE TITLE
Crash using Haskell `read` function

### ISSUE THREAD

**Issue by Swiip** [tweag/asterius#60]
After many tests, I isolated a crash in the wasm execution around the use of the native Haskell function `read`. Same code in standard Haskell works. Here is what I got:

```haskell
module Main where

import Asterius.Types

foreign export javascript "test" test :: IO ()

foreign import javascript "console.log(${1})" consoleLog :: JSString -> IO ()

test :: IO ()
test = do
       let arg = "21";
       let argParsed = read arg :: Int
       let result = argParsed * 2
       let resultSerialized = show result
       consoleLog (toJSString resultSerialized)

main :: IO ()
main = return ()
```
Compilation is fine but execution fails:
```
file:///root/2048/wasm/Main2.mjs:4
  throw err;
  ^

RuntimeError: unreachable
    at wasm-function[1468]:117
    at wasm-function[2318]:171
    at wasm-function[2281]:27
    at wasm-function[2454]:14
    at wasm-function[142]:5
    at file:///root/2048/wasm/Main2.mjs:12:40
```

After many tests, with Strings managed in a several ways. It's the `read` step which fails.

Any idea?

**Comment by TerrorJack** [comment]
Hi! So sorry for the late reply; we were occupied by #52 and didn't really have time to look into this one. That ticket is close to completion, and I'll definitely check this crash then.

Meanwhile, as [documented](https://tweag.github.io/asterius/ahc-link/#more-advanced-options-for-hackers), it's possible to add a `--debug` switch in addition to `--run` to `ahc-link`, and it will output a very comprehensive event log helpful to diagnose problems. Can you attach the log here as a gist, and specify the asterius revision you're using? Thanks a lot :D

**Comment by Swiip** [comment]
Hi, thanks to look at this. Here is what you ask (I think). Hope it helps, I don't understand anything ;)

For the version, I use the docker image, the latest when I submitted the issue. To be sure, I added the image inspection to the gist.

https://gist.github.com/Swiip/24affeaabdc62815c12d9c23bf4e80c4
