### ISSUE TITLE
support sbv library

### ISSUE THREAD

**Issue by shmish111** [tweag/asterius#613]
**Describe the bug**
https://www.stackage.org/package/sbv does not appear in https://github.com/tweag/asterius/issues/354
**To Reproduce**

**Expected behavior**
sbv should compile with asterius and be in the list of supported packages

**Environment**
 - OS name + version:
 - Version of the code:

**Additional context**

**Comment by TerrorJack** [comment]
I gave it a try and discovered `sbv-8.6` builds fine, as long as https://github.com/LeventErkok/sbv/pull/521 is applied.
