### ISSUE TITLE
Cloudflare Worker example is not working

### ISSUE THREAD

**Issue by CristhianMotoche** [tweag/asterius#676]
**Describe the bug**
Hello! I tried your [cloudflare](https://github.com/tweag/asterius/tree/master/asterius/test/cloudflare) example but it isn't working in Clouldfare workers. I'm getting the following error:

![image](https://user-images.githubusercontent.com/8370088/84324607-8cfe0080-ab3e-11ea-855d-662cf14ab577.png)

**To Reproduce**
1. Use the [cloudflare example](https://github.com/tweag/asterius/tree/master/asterius/test/cloudflare) and generate a `wasm` file and a `.js` file:

```sh
$ docker run --rm -it -v $(pwd):/project -w /project --user $(id -u):$(id -g) terrorjack/asterius
I have no name!@b03f004ccc7d:/project$ ahc-link \
  --input-hs cloudflare.hs \
  --no-main \
  --input-mjs cloudflare.mjs \
  --browser \
  --bundle \
  --export-function=handleFetch
```
2. Create a `metadata.json` file to push the `wasm` file to Cloudflare workers:
```json
{
  "body_part": "script",
  "bindings": [
    {
      "type": "wasm_module",
      "name": "wasm",
      "part": "wasm"
    }
  ]
}
```
3. Update your script with the wasm file:
```sh
curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/scripts/$SCRIPT_NAME" \
     -H  "Authorization: Bearer $CF_API_TOKEN" \
     -F "metadata=@metadata.json;type=application/json" \
     -F "script=@cloudflare.js;type=application/javascript" \
     -F "wasm=@cloudflare.wasm;type=application/wasm"
```
**NOTE:** You'd need a `$CF_ACCOUNT_ID`, `$SCRIPT_NAME` and `$CF_API_TOKEN`.

4. Access your cloudflare dashboard, go to Workers and select the worker that should named like `$SCRIPT_NAME` 

5. Click on `Quick Edit`. Once the editor is open, click on `Send`. You would see the error in the Console and a `500` error as worker response

**Expected behavior**
I'd expect the code to work in Cloudflare Workers. The worker should respond with a status code `200` and return the respective [output](https://github.com/tweag/asterius/blob/master/asterius/test/cloudflare/cloudflare.hs#L22): `Hello from Haskell`

**Environment**
 - OS name + version: Cloudflare Workers (?)
 - Version of the code: I'm using the latest version of asterius placed in the [docker](https://hub.docker.com/layers/terrorjack/asterius/latest/images/sha256-b07e8633fb5d69c24ca88da0f4c345ab441a4605b82ef345a5ca632274de4140?context=explore).

**Additional context**

**Comment by TerrorJack** [comment]
Thanks for reporting. It seems to be a recent new restriction in the worker runtime, and we need some work to revert #142 and enable users to synchronously instantiate an asterius instance so that the `fetch` event handler can be properly set up again. Will ping when we confirm an MVP is working again.

**Comment by juanpaucar** [comment]
@TerrorJack I was wondering if there's any plan to enable sync mode via flags again. I think that enabling it with a flag is useful in some cases like Cloudflare and I'd love to have it back. I would be very happy to open a new PR re-enabling it if that's of any help :)

**Comment by CristhianMotoche** [comment]
I tested the example again and it worked this time! I think it was an error in Cloudflare workers that I guess is fixed now. I'm closing this issue now.
