### ISSUE TITLE
Linker errors in setup phase (-lnuma, -lgmp)

### ISSUE THREAD

**Issue by ggreif** [tweag/asterius#681]
**Describe the bug**

upon running `stack build asterius` in a freshly cloned repo, I get errors with the excerpt below
```
/home/ggreif/asterius/asterius/asterius.cabal was modified manually. Ignoring /home/ggreif/asterius/asterius/package.yaml in favor of the cabal file.
If you want to use the package.yaml file instead of the cabal file,
then please delete the cabal file.
Linking /home/ggreif/.stack/setup-exe-cache/x86_64-linux-custom-asterius-tinfo6/tmp-Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 ...
/nix/store/3b3ighb83nhifa1v4n7855hlbdl1mhf9-binutils-2.31.1/bin/ld.gold: error: cannot find -lgmp
/nix/store/3b3ighb83nhifa1v4n7855hlbdl1mhf9-binutils-2.31.1/bin/ld.gold: error: cannot find -lnuma
/home/ggreif/.stack/programs/x86_64-linux/ghc-custom-asterius-tinfo6-8.8.3/lib/ghc-8.8.3/integer-gmp-1.0.2.0/libHSinteger-gmp-1.0.2.0.a(Type.o):function integerzmwiredzmin_GHCziIntegerziType_zdwplusBigNatWord_info: error: undefined reference to '__gmpn_add_1'

...

rts/posix/OSThreads.c:350:0: error:
     error: undefined reference to 'numa_run_on_node'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building simple Setup.hs using:
      /home/ggreif/.stack/programs/x86_64-linux/ghc-custom-asterius-tinfo6-8.8.3/bin/ghc-8.8.3 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-3.0.1.0 /home/ggreif/.stack/setup-exe-src/setup-mPHDZzAJ.hs /home/ggreif/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /home/ggreif/.stack/setup-exe-cache/x86_64-linux-custom-asterius-tinfo6/tmp-Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3
    Process exited with code: ExitFailure 1
```
Especially worrisome are the lines with `ld.gold: error: cannot find -lgmp` and `ld.gold: error: cannot find -lnuma`.
I have no idea how to supply the library paths that are necessary.

I tried adding
``` diff
+extra-lib-dirs:
+  - /nix/store/kvk59gjk0g2f3yd3sx53p55nb5lyi4pp-binaryen-93/lib
+  - /nix/store/9lnl22f66yqmdmk05mak6bgnl8c79g0z-numactl-2.0.13/lib
+  - /nix/store/wz4rxng4dpcwrlakqasl68y097bv4bmx-gmp-6.2.0/lib
```
to the `stack.yaml`, which didn't work.

**To Reproduce**

See above

**Expected behavior**

Asterius compiles via `stack` in a linux VM.

**Environment**
 - OS name + version:
```
Linux vm-ggreif 5.3.0-55-generic #49-Ubuntu SMP Thu May 21 12:47:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
 - `apt` environment
```
apt install libnuma-dev
```
 - Nix environment
```
ggreif@vm-ggreif:~/asterius$ nix-env -q
arcanist-20200127
binaryen-93
binutils-2.31.1
gcc-wrapper-9.3.0
gmp-6.2.0
gnumake-4.2.1
ninja-1.10.0
niv-0.2.13
nix-2.3.4
numactl-2.0.13
stack-2.3.1
swig-4.0.1
```
 - Version of the code: `master`

**Additional context**

**Comment by ggreif** [comment]
@TerrorJack sorry to bother, but do you have a quick idea how to fix this?

**Comment by ggreif** [comment]
This might be related to the kind of machine the custom compiler was built, cf. these Iines in `rts.cabal.in`:
```
flag libnuma
  default: @CabalHaveLibNuma@
```
So maybe the custom `x86_64-linux-custom-asterius-tinfo6` (and others) should be build with this flag `off`. Similarly to decrease dependencies on the environment, might I suggest to make the custom compilers use `integer-simple`?

**Comment by ggreif** [comment]
I hacked my way trough, by adding symlinks to the `libHS*` directories
pointing to the nix store dylibs. Also had to add a few extra `-optl
-L/..` flags to the GHC wrapper script.

So finally I could compile, some own programs to Wasm. There are two
dozen open imports, and I have to get those stubbed/implemented. Then
I may have a chance to run it on our Wasm-only platform.

One comment though, can you push a Darwin build that doesn't need
Catalina? Something like DEPLOYMENT_TARGET=10.13 yada-yada. I have
v10.13.6.

Thanks for the great work. I think this has big potential!

**Comment by TerrorJack** [comment]
The ghc bindists for `darwin` are built with github actions, and they only provide catalina runners at the moment. Not sure if older darwin versions can be built on that runtime though.

**Comment by ggreif** [comment]
I am pretty confident it can be customised with `runs-on : macos-10.13` somewhere. It is probably set to `macos-latest` now.

**Comment by ggreif** [comment]
Let's close this thread. I am is a rather unusual environment, so I am the one to cope with it.
