### ISSUE TITLE
PIC(Position Independent Code) support

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#723]
**Is your feature request related to a problem? Please describe.**
When #658 is implemented, dlmalloc in `wasi-libc` will take over control of the linear memory. In order to layout static data segments (e.g. info tables, static closures) in the memory, we need to call `malloc` to allocate the static data region. The returned address is only known at runtime.

This indicates that we need to generate PIC(Position Independent Code). Previously, at link-time, each symbol gets rewritten to its absolute address. Now, each symbol needs to be rewritten to a base address plus an offset. The offset is still known at link-time, but the base address is only known at run-time. The result of calling `malloc` will become an imported immutable global value, to be used as the base address. The combination of imported immutable global value plus a constant offset is permitted in function code and memory/table initialization.

One remaining problem is: what if the content of a data segment refers to a symbol? Since data segment contents must be vanilla buffers instead of wasm constant expressions, we can't directly put the base address + offset expression there. The solution is: the linker generates a function which corrects the data segment contents. That function is called only once when initializing the runtime.

**Describe the solution you'd like**
* Introduce the `env.__memory_base` `i32` global import
* All data addresses are rewritten to `TAG(env.__memory_base + offset)`. `offset` is also `i32`, and `TAG()` converts an `i32` physical address to our `i64` virtual address.
* At link-time, track all symbols in data segments, generate a `__wasm_apply_relocs` function which corrects the symbol contents given `env.__memory_base`
* Fix the symbol table logic in the runtime. All symbol table entries are offsets in the generated JavaScript artifact, and they must be rewritten to `TAG(env.__memory_base + offset)` as well.
* Apply the same to functions, using `env.__table_base` as the table offset
* Set the offsets to constant 1K in the runtime for now, before we actually call `malloc` to handle the memory.

**Describe alternatives you've considered**
Use `lld`'s `--global-base` flag to reserve a large unused linear memory region for static data when producing the `wasi-libc` module. The static data segments go to that region.

The main problem is: a different `wasi-libc` module must be linked each time we link an asterius module. Complicates the build system significantly. Given PIC will be required for dynamic loading anyway, might as well do it the proper way.

**Additional context**
https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md

**Comment by gkaracha** [comment]
Since this needs globals, it is currently blocked on #727.

**Comment by gkaracha** [comment]
@TerrorJack I think we can close this one, now that #750 has landed on master.

**Comment by TerrorJack** [comment]
Closed by #750.
