### ISSUE TITLE
Several ghc-testsuite tests fail with ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by gkaracha** [tweag/asterius#734]
**Describe the bug**

PR #724 revealed another major ghc-testsuite regression. Currently several of the tests in `ghc-testsuite` fail with the following error:
```
Exception: EvalError {evalErrorMessage = "TypeError [ERR_INVALID_ARG_TYPE]: The \"fd\" argument must be of type number. Received undefined
    at Object.writeSync (fs.js:677:3)
    at Device.MemoryFileSystem.files [as flush] (file:///tmp/-24566/node/default.mjs:40:26)
    at Device.write (file:///tmp/-24566/node/default.mjs:30:10)
    at MemoryFileSystem.writeSync (file:///tmp/-24566/node/default.mjs:50:27)
    at evalmachine.<anonymous>:1:192"}
```

**To Reproduce**
The easiest way to reproduce the issue is to run:
```
stack test asterius:ghc-testsuite
```
Currently many tests on my system fail with this error (`array/arr003`, `array/arr004`, `array/arr007`, `array/arr008`, `callarity/StrictLet`, `codeGen/CmmSwitchTestGen`, ...).

**Expected behavior**
All these tests should succeed.

**Environment**
 - OS name + version: Ubuntu 18.04.4 LTS (bionic)
 - Version of Asterius: current HEAD (https://github.com/tweag/asterius/commit/e7639b00fcd05a22c6f3be153343ac6210042a9a)

**Comment by TerrorJack** [comment]
Just figured out the cause of problem:

* In `ghc-testsuite`, we run compiled Haskell code via `inline-js-core` and fetch the `stdout`/`stderr` contents from a buffer
* `inline-js-core` runs everything in a `Worker` thread
* Our `node` runtime uses `process.stdout.fd` and `process.stderr.fd`
* According to `node` [documentation](https://nodejs.org/api/process.html#process_process_stdout_fd), `process.stdout.fd` and `process.stderr.fd` does not exist in a `Worker` context

**Comment by TerrorJack** [comment]
The current file system related logic in the runtime is way too chaotic for a confident refactor. I'll probably finish the work tomorrow instead.

We need to:

* Support `node` & browser
* For `node`, support being run in a `Worker` context
* Optionally keep a log of `stdout`/`stderr` for `ghc-testsuite`

I also took a look at wasi and see whether we can model the FS stuff based on the current wasi interface. The yak level is too high at the moment.
