### ISSUE TITLE
integer-simple vs integer-gmp

### ISSUE THREAD

**Issue by Fell-x27** [tweag/asterius#739]
Hi, I cant compile some project depends on "formatting" package. Because of "integer-gmp" is needed. Ok, I've loaded at manually, changed integer-gmp to integer-simple and everything looks fine, no more dependency problems but

`src/Data/Text/Format/Int.hs:108:13: error:
    Not in scope: data constructor ‘S#’
    Perhaps you meant ‘I#’ (imported from GHC.Types)
    |
108 | integer 10 (S# i#) = decimal (I# i#)
`

And there is no I can do. No, changing S# to I# doesn't help. I'm not a haskell developer, so it's hard for me to fix it.
Are there any ways to make it work with integer-simple?

**Comment by Fell-x27** [comment]
Well, just found solution for this package, but then stucked with another one, deeply-wired to integer-gmp. 

Can I hope, that it will be available? It was in early commits, but was removed then. Why?

**Comment by hsyl20** [comment]
#385 and #386 are related. The old integer-gmp support had some issues.
