### ISSUE TITLE
RangeError in garbage collector

### ISSUE THREAD

**Issue by pimlu** [tweag/asterius#97]
Hey, sorry for the lack of responsiveness after #29.  I tried fixing the bug but I still couldn't get it to work.  This is about something else though.

Anyway, I'm back at this and finally on the cusp of testing my [spaghetti application](https://github.com/pimlu/fractran) in webassembly.  The application is by nature CPU intensive. It runs (perfectly!) for a short moment before the garbage collector throws an error at [`rts.gc.mjs:294`](https://github.com/tweag/asterius/blob/f926cc60d948b53937efb7fcdafff5b1d263da7b/asterius/rts/rts.gc.mjs#L294).

The error is `RangeError: Offset is outside the bounds of the DataView`.  `fun_info` is big, almost 2^64.  The actual size of the DataView is 8388608, so maybe something is underflowing.

Would be happy to help debug on this side.

**Comment by pimlu** [comment]
I just discovered the tagging which explains why `fun_info` big. `Memory.unTag(p)` is 4143972352.

**Comment by TerrorJack** [comment]
Oh never mind, and thanks for reporting the gc issue!

I took a look at that repo; how do I run it? Is it just compiling `main.hs` and running that, or do I need to take care of `npm` stuff first?

**Comment by pimlu** [comment]
Hey, sorry about the mess and general badness (lol) in that repository, I just spent some time cleaning it up.  You can ignore everything NPM and ignore the `web` directory (that's the react project that integrates with my existing Haste build).

I made a branch designed to reproduce the GC issue: [fractran/asterius](https://github.com/pimlu/fractran/tree/asterius).  All it's designed to do is reproduce the GC issue using the main method of an Asterius browser build.  If you clone this repository, you should be able to reproduce via the following (also in README.md):

 * `git checkout asterius`
 * `./build.sh --browser`
 * `python3 serve.py`
 * Go to [localhost:8000/browser_test/main.html](http://localhost:8000/browser_test/main.html)
 * The browser might lock up for a moment while it processes, until the GC errors

**Comment by TerrorJack** [comment]
Excellent, thanks for the cleanup and instructions. Looking into this will take some time, but it's on my list now.

**Comment by TerrorJack** [comment]
Closing for now due to inactivity. There has been a lot of improvements in the storage manager since then; the bug is probably gone, but in case it persists, feel free to reopen.
